### ISSUE TITLE
Unable to use Z-coordinates? 

### ISSUE THREAD

**Issue by hlambrinoudis** [cisc3620/4-3d-viewer#5]
I have been able to create a projection for my model and have it spin along the y-axis, but the program does not seem to recognize any of the z coordinates that I have entered into the vertexes. I have modified the glVertexAttribPointer for posAttrib to:

glVertexAttribPointer(posAttrib, 3, GL_FLOAT, GL_FALSE, 6 * sizeof(GLfloat), 0);

but this did not seem to make any difference. 

@rivlev

**Comment by rivlev** [comment]
Have you modified the vertex shader?

**Comment by destroyer3b** [comment]
Maybe in the vertextsource 
`"in vec2 position;"               // expects 2 values for position`
did you change to 3?

**Comment by ZishanAhmed93** [comment]
For anyone having trouble.

with regards to the original main.cpp

on line 31 change
"in vec2 position;" 

to
"in vec3 position;" 

this makes position pass 3 values (x,y, and z) instead of 2(just x and y)

now since position is passing 3 values we also have to change line 38
"    gl_Position = model * vec4(position, 0.0, 1.0);" 
line 38 in it's original state is expected 2 values from position, then setting all z values to 0.0 and all w to 1.0.

but we just changed position to include the z coordinate so now we get rid of the extra 0.0.

Line 38 should now be.
"    gl_Position = model * vec4(position, 1.0);" 

Now regards to the vertices array. (line 51)
Originally,

GLfloat vertices [] = {
  MIDDLE, TOP, RED,
  LEFT, BOTTOM, BLUE,
  RIGHT, BOTTOM, GREEN,
};

this is sending 5 floats per line
MIDDLE & TOP are bot 1, and RED is 3 

(Since each color is 3 floats and each pos is 1 
ex
#define RED 1.0f, 0.0f, 0.0f       

#define MIDDLE 0.0f)

Now edit your vertices array to include a z values
use floats or make/reuse defines

(Side, i don't actually remember is z-axis near is negative so if thats wrong ignore it but just enter some z value)

ex.
#define NEAR -0.5f

GLfloat vertices [] = {
  MIDDLE, TOP, 0.5f , RED,
  LEFT, BOTTOM, MIDDLE BLUE,
  RIGHT, BOTTOM, NEAR, GREEN,
};

Lastly we edit line 128 and 132

Line 128
from
glVertexAttribPointer(posAttrib, 2, GL_FLOAT, GL_FALSE, 5 * sizeof(GLfloat), 0);

to
glVertexAttribPointer(posAttrib, 3, GL_FLOAT, GL_FALSE, 6 * sizeof(GLfloat), 0);

Line 132
from
glVertexAttribPointer(colAttrib, 3, GL_FLOAT, GL_FALSE, 5 * sizeof(GLfloat), (void*)(2 * sizeof(GLfloat)));

to
glVertexAttribPointer(colAttrib, 3, GL_FLOAT, GL_FALSE, 6 * sizeof(GLfloat), (void*)(3 * sizeof(GLfloat)));

this is because we are passing 3 positions instead of 2 (line 128) which means we now skip every 6 indexes (hence the 6 * sizeof(GLfloat)) and color also has to initially offset by 3 [the 3 in (void*)(3 * sizeof(GLfloat))].

After that pretty straight forward load your vertices array.

**Comment by rivlev** [comment]
@hlambrinoudis, please close if your problem is solved

**Comment by hlambrinoudis** [comment]
While I tried ZishanAhmed93's instructions, my model simply disappeared entirely instead, and I can't seem to find the cause. Could it be something wrong with my rendering loop that is causing errors? Here is what I have in there:

// Rendering Loop
  while (glfwWindowShouldClose(mWindow) == false) {
    
    // Background Fill Color
    glClearColor(0.85f, 0.65f, 0.65f, 0.8f);
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);

	t = t + 0.0001;
	glm::mat4 model;
	glm::mat4 view;
	glm::mat4 projection;
	model = glm::rotate(model, t, glm::vec3(0.0f, 0.25f, 0.0f));
	view = glm::translate(view, glm::vec3(0.0f, 0.0f, -2.0f));
	projection = glm::perspective(45.0f, (GLfloat)200 / (GLfloat)200, 0.1f, 100.0f);
	
	// Get their uniform location
	GLint modelLoc = glGetUniformLocation(shaderProgram, "model");
	GLint viewLoc = glGetUniformLocation(shaderProgram, "view");
	GLint projLoc = glGetUniformLocation(shaderProgram, "projection");
	
	// Pass them to the shaders
	glUniformMatrix4fv(modelLoc, 1, GL_FALSE, glm::value_ptr(model));
	glUniformMatrix4fv(viewLoc, 1, GL_FALSE, glm::value_ptr(view));
	glUniformMatrix4fv(projLoc, 1, GL_FALSE, glm::value_ptr(projection));

    // draw triangle
	glBindVertexArray(vao);
    glDrawArrays(GL_TRIANGLES, 3, 9);
	glBindVertexArray(0);
    
    // Flip Buffers and Draw
    glfwSwapBuffers(mWindow);
    glfwPollEvents();
  }glfwTerminate();

**Comment by rivlev** [comment]
Usually when things disappear something is mismatched or not linked up correctly between the application and the shader.

crude debugging: try just drawing the position without multiplying by any transformation matrices. Then add the matrices one by one. check the names of everything very carefully (the matrices must be called exactly "model" "view" and "projection" in your shader).

**Comment by destroyer3b** [comment]
For me I had to change the version to 330, not sure if that is for you.

**Comment by hlambrinoudis** [comment]
Alright, I've finally managed to get a rotating 3D model now.  While I ended up removing the view and projection matrices, the model is fully 3D and rotates along the Y-axis.
